USE amazon_ecommerce_sales;

-- =========================================================
-- AMAZON E-COMMERCE SALES ANALYSIS
-- PRODUCT ANALYSIS
-- =========================================================


-- 1. Display all products
SELECT DISTINCT
    product_id,
    product_name,
    category,
    unit_price
FROM amazon_sales
ORDER BY product_id;


-- 2. Total number of products
SELECT
    COUNT(DISTINCT product_id) AS total_products
FROM amazon_sales;


-- 3. Products by category
SELECT
    category,
    COUNT(DISTINCT product_id) AS total_products
FROM amazon_sales
GROUP BY category
ORDER BY total_products DESC;


-- 4. Total quantity sold for each product
SELECT
    product_id,
    product_name,
    category,
    SUM(quantity) AS total_units_sold
FROM amazon_sales
GROUP BY product_id, product_name, category
ORDER BY total_units_sold DESC;


-- 5. Total revenue generated by each product
SELECT
    product_id,
    product_name,
    category,
    ROUND(
        SUM(
            (quantity * unit_price)
            - ((quantity * unit_price) * discount / 100)
        ),
        2
    ) AS total_revenue
FROM amazon_sales
GROUP BY product_id, product_name, category
ORDER BY total_revenue DESC;


-- 6. Top 10 products by revenue
SELECT
    product_id,
    product_name,
    category,
    ROUND(
        SUM(
            (quantity * unit_price)
            - ((quantity * unit_price) * discount / 100)
        ),
        2
    ) AS revenue
FROM amazon_sales
GROUP BY product_id, product_name, category
ORDER BY revenue DESC
LIMIT 10;


-- 7. Top 10 products by quantity sold
SELECT
    product_id,
    product_name,
    category,
    SUM(quantity) AS units_sold
FROM amazon_sales
GROUP BY product_id, product_name, category
ORDER BY units_sold DESC
LIMIT 10;


-- 8. Lowest-selling products
SELECT
    product_id,
    product_name,
    category,
    SUM(quantity) AS units_sold
FROM amazon_sales
GROUP BY product_id, product_name, category
ORDER BY units_sold ASC
LIMIT 10;


-- 9. Highest-priced products
SELECT
    product_id,
    product_name,
    category,
    unit_price
FROM amazon_sales
GROUP BY product_id, product_name, category, unit_price
ORDER BY unit_price DESC
LIMIT 10;


-- 10. Lowest-priced products
SELECT
    product_id,
    product_name,
    category,
    unit_price
FROM amazon_sales
GROUP BY product_id, product_name, category, unit_price
ORDER BY unit_price ASC
LIMIT 10;


-- 11. Average price by category
SELECT
    category,
    ROUND(AVG(unit_price), 2) AS average_price
FROM amazon_sales
GROUP BY category
ORDER BY average_price DESC;


-- 12. Average rating by product
SELECT
    product_id,
    product_name,
    category,
    ROUND(AVG(rating), 2) AS average_rating
FROM amazon_sales
GROUP BY product_id, product_name, category
ORDER BY average_rating DESC;


-- 13. Products with rating above 4.5
SELECT
    product_id,
    product_name,
    category,
    ROUND(AVG(rating), 2) AS average_rating
FROM amazon_sales
GROUP BY product_id, product_name, category
HAVING AVG(rating) > 4.5
ORDER BY average_rating DESC;


-- 14. Products with rating below 4.2
SELECT
    product_id,
    product_name,
    category,
    ROUND(AVG(rating), 2) AS average_rating
FROM amazon_sales
GROUP BY product_id, product_name, category
HAVING AVG(rating) < 4.2
ORDER BY average_rating ASC;


-- 15. Total discount given for each product
SELECT
    product_id,
    product_name,
    ROUND(
        SUM(
            (quantity * unit_price) * discount / 100
        ),
        2
    ) AS total_discount
FROM amazon_sales
GROUP BY product_id, product_name
ORDER BY total_discount DESC;


-- 16. Average discount by product
SELECT
    product_id,
    product_name,
    ROUND(AVG(discount), 2) AS average_discount
FROM amazon_sales
GROUP BY product_id, product_name
ORDER BY average_discount DESC;


-- 17. Gross sales vs net revenue
SELECT
    product_id,
    product_name,

    ROUND(
        SUM(quantity * unit_price),
        2
    ) AS gross_sales,

    ROUND(
        SUM(
            (quantity * unit_price)
            - ((quantity * unit_price) * discount / 100)
        ),
        2
    ) AS net_revenue

FROM amazon_sales
GROUP BY product_id, product_name
ORDER BY net_revenue DESC;


-- 18. Product revenue contribution percentage
SELECT
    product_id,
    product_name,
    category,

    ROUND(
        SUM(
            (quantity * unit_price)
            - ((quantity * unit_price) * discount / 100)
        ),
        2
    ) AS revenue,

    ROUND(
        SUM(
            (quantity * unit_price)
            - ((quantity * unit_price) * discount / 100)
        )
        /
        (
            SELECT
                SUM(
                    (quantity * unit_price)
                    - ((quantity * unit_price) * discount / 100)
                )
            FROM amazon_sales
        ) * 100,
        2
    ) AS revenue_percentage

FROM amazon_sales
GROUP BY product_id, product_name, category
ORDER BY revenue_percentage DESC;


-- 19. Products generating more than ₹10,000
SELECT
    product_id,
    product_name,
    category,

    ROUND(
        SUM(
            (quantity * unit_price)
            - ((quantity * unit_price) * discount / 100)
        ),
        2
    ) AS revenue

FROM amazon_sales
GROUP BY product_id, product_name, category

HAVING revenue > 10000

ORDER BY revenue DESC;


-- 20. Products selling more than 5 units
SELECT
    product_id,
    product_name,
    category,
    SUM(quantity) AS units_sold
FROM amazon_sales
GROUP BY product_id, product_name, category
HAVING SUM(quantity) > 5
ORDER BY units_sold DESC;


-- 21. Products sold in multiple cities
SELECT
    product_id,
    product_name,
    COUNT(DISTINCT customer_city) AS cities
FROM amazon_sales
GROUP BY product_id, product_name
HAVING COUNT(DISTINCT customer_city) > 1
ORDER BY cities DESC;


-- 22. Products purchased using multiple payment methods
SELECT
    product_id,
    product_name,
    COUNT(DISTINCT payment_method) AS payment_methods
FROM amazon_sales
GROUP BY product_id, product_name
HAVING COUNT(DISTINCT payment_method) > 1
ORDER BY payment_methods DESC;


-- 23. Product sales by category
SELECT
    category,

    COUNT(DISTINCT product_id) AS products,

    SUM(quantity) AS units_sold,

    ROUND(
        SUM(
            (quantity * unit_price)
            - ((quantity * unit_price) * discount / 100)
        ),
        2
    ) AS revenue,

    ROUND(AVG(rating), 2) AS average_rating

FROM amazon_sales
GROUP BY category
ORDER BY revenue DESC;


-- 24. Product performance classification
SELECT
    product_id,
    product_name,
    category,

    SUM(quantity) AS units_sold,

    ROUND(
        SUM(
            (quantity * unit_price)
            - ((quantity * unit_price) * discount / 100)
        ),
        2
    ) AS revenue,

    CASE
        WHEN SUM(quantity) >= 8 THEN 'High Selling Product'
        WHEN SUM(quantity) >= 4 THEN 'Medium Selling Product'
        ELSE 'Low Selling Product'
    END AS sales_category

FROM amazon_sales
GROUP BY product_id, product_name, category
ORDER BY units_sold DESC;


-- 25. Complete product performance report
SELECT
    product_id,
    product_name,
    category,

    COUNT(DISTINCT order_id) AS total_orders,

    SUM(quantity) AS total_units_sold,

    ROUND(AVG(unit_price), 2) AS average_price,

    ROUND(AVG(discount), 2) AS average_discount,

    ROUND(
        SUM(
            (quantity * unit_price)
            - ((quantity * unit_price) * discount / 100)
        ),
        2
    ) AS total_revenue,

    ROUND(AVG(rating), 2) AS average_rating

FROM amazon_sales

GROUP BY
    product_id,
    product_name,
    category

ORDER BY total_revenue DESC;
